### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by jason-t-fu** [jason-t-fu/Feathernote#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

---
## Comments
* I am not able to sign up a new user - when I try to I get the error 'Invalid Credentials' - seems like you're dispatching `login` on the signup page, instead of `signup`. For this reason I have unchecked both boxes relating to signing up.
![screen shot 2019-02-28 at 9 41 16 am](https://user-images.githubusercontent.com/32026924/53586437-084fc480-3b3d-11e9-8730-0a8df51048ba.png)
* Make sure to properly implement log out once you have a page that the user can actually redirect to after sign in
* You need a `<Redirect to="/" />` at the bottom of your `Switch` statement in `App.jsx` => right now if I go to a random route I get a blank page, but should either be getting a 404 or redirected back to your home page.
* Footer styling is a little different from theirs => they have all the footer content below the black line, whereas all of yours is above the black line. Seems only the logo should be above the black line
![screen shot 2019-02-28 at 9 34 22 am](https://user-images.githubusercontent.com/32026924/53586066-3a145b80-3b3c-11e9-8ba0-6cf199a379d9.png)
![screen shot 2019-02-28 at 9 34 31 am](https://user-images.githubusercontent.com/32026924/53586067-3a145b80-3b3c-11e9-9a1b-638fb0ff084a.png)

**Comment by ronilbhatia** [comment]
Hey Jason,

Overall good job putting this together. See my comments above on things that need to change and we can close this issue out! The footer styling is lowest priority, but I would like you to close out the other 3 bullets ASAP before moving on to other parts of your app. Good job removing your logger from production and having errors disappear between signup and login!

**Comment by jason-t-fu** [comment]
Hey Ronil,

The issues should be fixed now, let me know any of them are still broken.

**Comment by ronilbhatia** [comment]
Good job! Looks like you fixed it all. There is one bug I'm getting now though which is that when I try to do the demo login from the 'Sign Up' page I get this error. I think it's because you are using the demo login credentials to try to sign up a new user rather than log them in. Make sure that you are dispatching `login` and not `signup` for your demo button on the signup page.
